# Classificação

In [2]:
import numpy as np
import pandas as pd

from sklearn.metrics import classification_report, confusion_matrix  
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier  

In [3]:
# Load gun laws dataset
gun_laws = pd.read_csv('../databases/gun_laws.zip', compression='zip')

states = pd.read_csv('../databases/states.zip', compression='zip')

state  Red Flag Laws  Relinquishment Laws  \
0                Alabama              0                    0   
1                 Alaska              0                    0   
2                Arizona              0                    0   
3               Arkansas              0                    0   
4             California              1                    1   
5               Colorado              0                    0   
6            Connecticut              1                    1   
7               Delaware              0                    0   
8   District of Columbia              0                    0   
9                Florida              0                    0   
10               Georgia              0                    0   
11                Hawaii              0                    1   
12                 Idaho              0                    0   
13              Illinois              0                    1   
14               Indiana              1                    0   
15                  Iowa              0                    0   
16                Kansas              0                    0   
17              Kentucky              0                    0   
18             Louisiana              0                    0   
19                 Maine              0                    0   
20              Maryland              0                    0   
21         Massachusetts              0                    1   
22              Michigan              0                    0   
23             Minnesota              0                    0   
24           Mississippi              0                    0   
25              Missouri              0                    0   
26               Montana              0                    0   
27              Nebraska              0                    0   
28                Nevada              0                    0   
29         New Hampshire              0                    0   
30            New Jersey              0                    0   
31            New Mexico              0                    0   
32              New York              0                    1   
33        North Carolina              0                    0   
34          North Dakota              0                    0   
35                  Ohio              0                    0   
36              Oklahoma              0                    0   
37                Oregon              1                    0   
38          Pennsylvania              0                    1   
39          Rhode Island              0                    0   
40        South Carolina              0                    0   
41          South Dakota              0                    0   
42             Tennessee              0                    0   
43                 Texas              0                    0   
44                  Utah              0                    0   
45               Vermont              0                    0   
46              Virginia              0                    0   
47            Washington              1                    0   
48         West Virginia              0                    0   
49             Wisconsin              0                    0   
50               Wyoming              0                    0   

    Assault Weapon Ban  High-Capacity Magazine ban  \
0                    0                           0   
1                    0                           0   
2                    0                           0   
3                    0                           0   
4                    1                           1   
5                    0                           1   
6                    1                           1   
7                    0                           0   
8                    1                           1   
9                    0                           0   
10                   0                           0   
11                   0                    

In [3]:
# Classify each state by number of incidents
state_class = np.concatenate((np.repeat('low', 17), np.repeat('medium', 17), np.repeat('high', 17)))

states = states.sort_values(by='incidents_per_capita')
states['class'] = state_class

# Create labeled dataset
gun_laws_class = pd.merge(states[['state', 'class']], gun_laws, on='state')

# Split train and test sets
y = gun_laws_class['class']
X = gun_laws_class.drop(['state', 'class'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

# Train
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1 0 3]
 [2 0 3]
 [2 0 0]]
              precision    recall  f1-score   support

        high       0.20      0.25      0.22         4
         low       0.00      0.00      0.00         5
      medium       0.00      0.00      0.00         2

   micro avg       0.09      0.09      0.09        11
   macro avg       0.07      0.08      0.07        11
weighted avg       0.07      0.09      0.08        11



/home/marcelo/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
